name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: setup-flutter
      uses: takuyaohashi/setup-flutter@v1
      #with:
        # The Flutter version to download
        #flutter-version: # optional, default is latest
        # The Flutter channel to download
        #channel: # optional, default is stable
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter pub run test
